services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: country_etl
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=country_etl
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - .:/app
    command: python main.py

volumes:
  postgres_data: